name: "Sphinx: Render docs"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install Sphinx & Dependencies
      run: pip install sphinx sphinx_markdown_builder sphinx_rtd_theme sphinx-argparse m2r
    - name: Install bean
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision torchaudio
        pip install -r requirements.txt
        pip install -e .
    - name: Build Documentation
      run: cd "$GITHUB_WORKSPACE/docs" && sphinx-build . _build

    - uses: actions/upload-artifact@v3
      with:
        name: Documentation
        path: "$GITHUB_WORKSPACE/docs/_build/html/"
