name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    environment: 
      name: pypi
      url: https://pypi.org/p/crispr-bean
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install pypa/setuptools
      run: >-
        python -m
        pip install wheel numpy setuptools Cython auditwheel
    - name: Extract tag name
      id: tag
      run: echo ::set-output name=TAG_NAME::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Build a binary wheel
      run: |
        python setup.py sdist bdist_wheel
        auditwheel repair dist/bean-${{ steps.tag.outputs.TAG_NAME }}-cp38-cp38-linux_x86_64.whl --plat manylinux_2_24_x86_64
        mv wheelhouse/* dist
        rm dist/*-cp38-cp38-linux_x86_64.whl
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}